# Challenges

## Purpose
A review on Python programming

## Methodology
Review basic operations, types and programming concepts in Python. Solve programming challenges.

## Progress 
- 2022-02-20 21:02:54 ready
- 2022-01-28 15:34:59 start

## Results  
Fast track to programming in Python.

## Suggested next steps

Don't skip the exercises before moving forward

## Setup

### Library import

In [2]:
import numpy as np

#### Numpy

The fundamental package for scientific computing with Python

<img src="https://numpy.org/images/logo.svg" width="100" height="100">

[NumPy](https://numpy.org/)

# Review

## Types

https://docs.python.org/3.6/library/stdtypes.html

### Boolean

- True 
- False

In [4]:
True

True

In [5]:
False

False

In [6]:
type(True)

bool

#### Boolean Operations 

Suppose variables x and y  

    
<table><thead>
<tr>
<th style="text-align: center">Operator</th>
<th>Description</th>
<th>Code</th>
</tr>
</thead><tbody>
<tr>
<td style="text-align: center">and</td>
<td>True if both are true</td>
<td><code>x and y</code></td>
</tr>
<tr>
<td style="text-align: center">or</td>
<td>True if at least one is true</td>
<td><code>x or y</code></td>
</tr>
<tr>
<td style="text-align: center">not</td>
<td>True only if false</td>
<td><code>not x</code></td>
</tr>
</tbody></table>

In [7]:
a = True
b = False

In [8]:
a and b

False

In [9]:
a and not b

True

---

###  Numeric 
- int
- float

In [10]:
a_integer = 2
type(a_integer)

int

In [11]:
a_float = 2.0
type(a_float)

float

Cast from Float to Integer

In [12]:
int(2.0)

2

Cast from Integer to Float

In [13]:
float(2)

2.0

---

### Sequence Types

#### Text Sequence or String

In [14]:
a_string = "A"
type(a_string)

str

Concatenate Strings

In [15]:
"A" + "B"

'AB'

---

#### List,  Mutable Dynamic Arrays


Empty List

In [16]:
list_array = []
list_array

[]

Multiple types 

In [17]:
list_array = ["one", "two", 3, 4.0]
list_array

['one', 'two', 3, 4.0]

Mutability

In [18]:
list_array[1] = "A"
list_array

['one', 'A', 3, 4.0]

Append at the end

In [19]:
list_array.append("Data")
list_array.append("Science")
list_array.append("Intro")
list_array.append(10)
list_array

['one', 'A', 3, 4.0, 'Data', 'Science', 'Intro', 10]

Remove at the end

In [20]:
list_array.pop()
list_array

['one', 'A', 3, 4.0, 'Data', 'Science', 'Intro']

Remove Operation by index

In [21]:
del list_array[1]
list_array

['one', 3, 4.0, 'Data', 'Science', 'Intro']

Size of list

In [41]:
len(list_array)

6

Indexing or **Slicing** List

```python
start:end(exclusive):step
```

From first to second, all values

In [46]:
list_array[0:2:1]

['one', 3]

From first to fourth, every two values

In [47]:
list_array[0:4:2]

['one', 4.0]

---

#### Range

In [22]:
range(4)

range(0, 4)

In [23]:
list(range(0,4))

[0, 1, 2, 3]

---

#### Tuples

In [2]:
a_tuple = ("one", "two", "three")
a_tuple

('one', 'two', 'three')

Tuples are immutable! For example, if you try to update or delete one value it will return an error

In [25]:
a_tuple[1] = "hello"

TypeError: 'tuple' object does not support item assignment

In [ ]:
del a_tuple[1]

Adding elements to a tuple creates a new one

In [3]:
a_second_tuple = a_tuple + (23,)
a_second_tuple

('one', 'two', 'three', 23)

Memory address of each variable

In [4]:
id(a_tuple)

140484526322864

In [5]:
id(a_second_tuple)

140484526352048

In [6]:
a_tuple is a_second_tuple

False

---

### Mapping Types

#### Dictionary

The **Dictionary** is a mapping object that maps hashable values to arbitrary objects.

A dictionary is composed of *keys* and *values* and *keys* need to hashable.  

For example `{'data': 0, 'science': 0}`


In [7]:
a_dict = dict()
a_dict

{}

In [8]:
a_dict = {}
a_dict

{}

In [9]:
a_dict = {1: 2}
a_dict

{1: 2}

In [10]:
type(a_dict)

dict

In [11]:
a_dict = {'data': 2, 1: 2, 'science': 4}
a_dict

{'data': 2, 1: 2, 'science': 4}

Acess value with the key ```data```

In [12]:
a_dict['data']

2

Delete entry with the key ```data```

In [13]:
del a_dict['data']

In [14]:
a_dict

{1: 2, 'science': 4}

---

## Membership Operators

In [15]:
4.0 in [ 1, 2, 3, 4]

True

---

## Control Flow Tools

### For Statements

```python
    for element in a_collection:
        do something
```

In [32]:
for value in [1,2,3,4]:

    print(value)

1
2
3
4


### If Statements

```python
    if condition:
        do something
    else:
        do something
```

In [ ]:
if 2 > 4:
    print("2 > 4")
else:
    print("2 <= 4")

### Common use of Range

```python
    for element in range(limit):
        do something
```

In [31]:
for value in range(4):

    print(value)

0
1
2
3


In [50]:
a_list = [10,20,30]
for idx in range(len(a_list)):
    
    print(idx, a_list[idx])

0 10
1 20
2 30


### List Comprehensions

Create lists with elements with a single statement

```python
[ a_value for a_value in a_collection ]

```

In [29]:
[ a_value + 10 for a_value in [1,2,3,4,5] ]

[11, 12, 13, 14, 15]

List comprehension with conditions

In [56]:
[ a_value + 10 for a_value in [1,2,3,4,5] if a_value >= 3 ]

[13, 14, 15]

---

## Functions


```python
def functionName(argument_one, argument_two):
    """
    Comment what it does
    """
    
    
    do_stuff
    
    return value
```


### Call a function

```python
functionName(argument_one, argument_two)
```

In [ ]:
def soma(x, y):
    """
    Return the sum between x and y
    """

    return x + y

In [ ]:
soma(2, 4)

### Built-in Functions

#### Zip

```python
one = [1,2]
two = [3,4]
for value_from_one, value_from_two in zip(one, two):
    do something
```

In [26]:
one = [1,2]
two = [3,4]
for value_from_one, value_from_two in zip(one, two):
    print(value_from_one, value_from_two)

1 3
2 4


---

## Code Standards

PEP 8 

[PEP 8: Function and Variable Names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)  

**Summary**
 - Use Snake case in functions and variables, lowercase with words separated by underscores as necessary to improve readability
     - data_science  


 - For constants use all capital letters with underscores separating words
     - DATA_SCIENCE  


 - Use CapWords convention for classes
     - DataScience

# Challenges

**Reminder**   
The built-in type ```range```

*The range type represents an immutable sequence of numbers and is commonly used for looping a specific number of times in for loops.*[[source]](https://docs.python.org/3.3/library/stdtypes.html?highlight=range#ranges)


```python
range(stop) -> range object
range(start, stop[, step]) -> range object
```

1. Use a função arange de numpy para criar um vetor chamado my_array com a sequencia de números desde zero até 24 (exclusivo)

2. Use a função reshape para redimensionar o vetor de tal forma que fique com seis filas e cinco colunas. Que acontece? Qual é a relação entre número de elementos e a dimensão duma matrix bi-dimensional?

3. Sendo que temos 24 elementos, identifique duas combinações de dimensões que permitam redimensionar este vector em forma de matriz.

## Matrix 

$$\begin{bmatrix} 
1 & 2 & 1 & 7 \\ 
3 & 0 & 1 & 8 \\ 
0 & 2 & 4 & 9 \\ 
2 & 2 & 5 & 5
\end{bmatrix}$$

1. Create the matrix using numpy
2. Slice the 1st column
3. Slice the 1st column and rows 2 and 3 (inclusive)
4. Slice the four elements in the center of the matrix
5. Slice a sub-matrix with the four elements on the squared bottom right region
6. Solve the 5th question using the matrix size

```python
# first column: 
 [1 3 0 2] 

#first column, rows 2 and 3: 
 [3 0] 

# centre: 
 [[0 1]
  [2 4]] 
    
# bottom right: 
 [[4 9]
  [5 5]] 

#top right: 
 [[1 7]
  [1 8]]
```

## List and Dictionary comprehensions

### Find all of the numbers from 1–1000 that have a 3 in them

###  Find all of the words in a string that are less than 7 letters

### Use a dictionary comprehension to count the length of each word in a sentence

### Use a nested list comprehension to find all of the numbers from 1–1000 that are divisible (no reminder) by any single digit besides number 1

## Functions

### Compute the discount
Create a function in Python that accepts two parameters. The first should be the full price of an item. The second should be the discount percentage.

The function should return the price of the item after the discount has been applied.

For example, parameters (100, 20) should return 80

### Create a calculator 
Write a Python function that accepts three parameters.  
- The first parameter is a numeric value.
- The second is one of the following mathematical operators: +, -, /, or .
- The third parameter will also be a numeric value

The function should perform a calculation and return the results.

For example, parameters (2.5, '.', 3) should return 7.5

### Return me the numbers
Write a function in Python that accepts a list of any length that contains a mix of numbers and strings. The function should return a list with only the numeric values in the original list in the same order with decimal values rounded.

For example, passing the list [3, 'hi', 5, 5.6] should return [3, 5, 6]